services:
  rabbitmq:
    image: rabbitmq:4-management
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: harvester
      RABBITMQ_DEFAULT_PASS: yoursecretsecret
    ports:
      - "15672:15672"
