"""add input/ouput

Revision ID: ac123157b86e
Revises: b0f5b86e0828
Create Date: 2026-08-25 15:52:07.426935

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ac123157b86e"
down_revision: Union[str, Sequence[str], None] = "b0f5b86e0828"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('tool_metadata', sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # op.add_column('tool_metadata', sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###
    op.add_column(
        "tool_metadata",
        sa.Column(
            "inputs",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )

    op.alter_column(
        "tool_metadata",
        "inputs",
        server_default=None,
    )
    op.add_column(
        "tool_metadata",
        sa.Column(
            "outputs",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )

    op.alter_column(
        "tool_metadata",
        "outputs",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tool_metadata", "outputs")
    op.drop_column("tool_metadata", "inputs")
    # ### end Alembic commands ###
