"""add organization to tool metadata

Revision ID: b0f5b86e0828
Revises: df16ea4bf96a
Create Date: 2026-08-25 12:53:58.892516

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b0f5b86e0828"
down_revision: Union[str, Sequence[str], None] = "df16ea4bf96a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "tool_metadata",
        sa.Column(
            "organizations",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )

    # op.alter_column(
    #     "tool_metadata",
    #     "organizations",
    #     server_default=None,
    # )
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('tool_metadata', sa.Column('organizations', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tool_metadata", "organizations")
    # ### end Alembic commands ###
