"""add unique contraint for harvested tool versions

Revision ID: df16ea4bf96a
Revises: 47f08ec11ff1
Create Date: 2026-08-25 10:24:44.786596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df16ea4bf96a'
down_revision: Union[str, Sequence[str], None] = '47f08ec11ff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tool_metadata', 'quality_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_unique_constraint('uq_tool_metadata_source_url_identifier_version', 'tool_metadata', ['source_url', 'source_identifier', 'version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tool_metadata_source_url_identifier_version', 'tool_metadata', type_='unique')
    op.alter_column('tool_metadata', 'quality_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
