from __future__ import annotations

import argparse
import logging
from datetime import datetime
from pathlib import Path

from sqlalchemy import func
from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.orm import Session

from toolmeta_harvester.db.engine import engine
from toolmeta_harvester.db.models import (
    Base,
    ToolMetadata,
    HarvestResult,
)
from toolmeta_harvester.extractors.jsonld import (
    jsonld_defines_tool,
)
from toolmeta_harvester.extractors.tool_metadata import (
    extract_tool_metadata,
)
from toolmeta_harvester.quality.metadata_quality import (
    assess_metadata_quality,
)
from toolmeta_harvester.tasks.zenodo_jsonld import (
    download_zenodo_jsonld,
    get_zenodo_record,
    parse_zenodo_url,
)
from toolmeta_harvester.flows.decorators import dynamic_harvest


PIPELINE_VERSION = "0.1.0"

PIPELINE_TAG = (
    f"{__name__.rsplit('.', 1)[-1].removeprefix('harvest_')}@{PIPELINE_VERSION}"
)

LOG_FILE = Path("logs/harvest_zenodo.log")

LOG_FILE.parent.mkdir(
    parents=True,
    exist_ok=True,
)

logging.basicConfig(
    level=logging.INFO,
    format=("%(asctime)s %(name)s %(levelname)s: %(message)s"),
    handlers=[
        logging.StreamHandler(),
        logging.FileHandler(LOG_FILE),
    ],
)

logger = logging.getLogger(__name__)


def parse_datetime(
    value,
):
    if not value:
        return None

    if isinstance(
        value,
        datetime,
    ):
        return value

    try:
        return datetime.fromisoformat(
            str(value).replace(
                "Z",
                "+00:00",
            )
        )

    except (
        TypeError,
        ValueError,
    ):
        logger.warning(
            "Unable to parse datetime: %r",
            value,
        )

        return None


def get_zenodo_source_url(
    record_id: str,
) -> str:
    return f"https://zenodo.org/records/{record_id}"


def upsert_tool_metadata(
    session: Session,
    record: ToolMetadata,
) -> None:
    """
    Insert or update a Zenodo tool record.

    Logical identity:
        source_url + source_identifier

    harvested_at is generated by PostgreSQL on INSERT and
    refreshed on UPDATE.
    """

    excluded_from_insert = {
        "id",
        "harvested_at",
    }

    values = {
        column.name: getattr(
            record,
            column.name,
        )
        for column in ToolMetadata.__table__.columns
        if column.name not in excluded_from_insert
    }

    stmt = insert(ToolMetadata).values(**values)

    excluded = stmt.excluded

    excluded_from_update = {
        "id",
        "source_url",
        "source_identifier",
        "harvested_at",
    }

    update_values = {
        column.name: getattr(
            excluded,
            column.name,
        )
        for column in ToolMetadata.__table__.columns
        if column.name not in excluded_from_update
    }

    update_values["harvested_at"] = func.now()

    stmt = stmt.on_conflict_do_update(
        constraint=("uq_tool_metadata_source"),
        set_=update_values,
    )

    session.execute(stmt)


def create_tool_metadata(
    record: dict,
    raw_metadata: dict,
    metadata_url: str,
    pipeline_tag: str = PIPELINE_TAG,
) -> ToolMetadata:
    """
    Convert Zenodo JSON-LD into the canonical ToolMetadata model.
    """

    metadata = extract_tool_metadata(raw_metadata)

    quality = assess_metadata_quality(metadata)

    record_id = str(record.get("id"))

    source_url = get_zenodo_source_url(record_id)

    version = metadata.get("version")

    if version is not None:
        version = str(version)

    return ToolMetadata(
        quality_score=(quality.score),
        # -----------------------------------------------------
        # Provenance
        # -----------------------------------------------------
        pipeline_tag=(pipeline_tag),
        source_identifier=(record_id),
        source_url=(source_url),
        metadata_url=(metadata_url),
        # This is the format actually harvested from Zenodo.
        metadata_format=("json-ld"),
        metadata_version=(metadata.get("metadata_version")),
        # -----------------------------------------------------
        # CodeMeta / schema.org
        # -----------------------------------------------------
        title=metadata.get("title"),
        description=metadata.get("description"),
        raw_description=metadata.get("raw_description"),
        version=version,
        license=metadata.get("license"),
        identifiers=metadata.get(
            "identifiers",
            [],
        ),
        url=(metadata.get("url") or source_url),
        code_repository=(metadata.get("code_repository")),
        keywords=metadata.get(
            "keywords",
            [],
        ),
        authors=metadata.get(
            "authors",
            [],
        ),
        organizations=metadata.get(
            "organizations",
            [],
        ),
        types=metadata.get(
            "types",
            [],
        ),
        programming_languages=(
            metadata.get(
                "programming_languages",
                [],
            )
        ),
        runtime_platforms=(
            metadata.get(
                "runtime_platforms",
                [],
            )
        ),
        software_requirements=(
            metadata.get(
                "software_requirements",
                [],
            )
        ),
        # -----------------------------------------------------
        # CodeMeta scientific extensions
        # -----------------------------------------------------
        software_types=metadata.get(
            "software_types",
            [],
        ),
        consumes_data=metadata.get(
            "consumes_data",
            [],
        ),
        produces_data=metadata.get(
            "produces_data",
            [],
        ),
        inputs=metadata.get(
            "inputs",
            [],
        ),
        outputs=metadata.get(
            "outputs",
            [],
        ),
        # -----------------------------------------------------
        # Dates
        # -----------------------------------------------------
        date_created=parse_datetime(metadata.get("date_created")),
        date_published=parse_datetime(metadata.get("date_published")),
        date_modified=parse_datetime(metadata.get("date_modified")),
        # Preserve the actual metadata representation harvested
        # from Zenodo.
        raw_metadata=raw_metadata,
    )


@dynamic_harvest(
    name="zenodo",
    default_schedule="0 3 * * *",
)
def pipeline_harvest_zenodo(
    zenodo_url: str,
) -> HarvestResult:
    """
    Harvest one Zenodo record using its JSON-LD export.

    Processing:

        Zenodo URL
            ↓
        /export/json-ld
            ↓
        validate software/tool entity
            ↓
        extract_tool_metadata()
            ↓
        quality assessment
            ↓
        ToolMetadata
            ↓
        PostgreSQL upsert
    """

    Base.metadata.create_all(engine)

    record_id = parse_zenodo_url(zenodo_url)

    # Retrieve the normal Zenodo API record primarily for
    # provenance / record identity.
    record = get_zenodo_record(record_id)

    with Session(
        engine,
        expire_on_commit=False,
    ) as session:
        try:
            logger.info(
                "Retrieving JSON-LD from Zenodo record %s",
                record_id,
            )

            (
                raw_metadata,
                metadata_url,
            ) = download_zenodo_jsonld(record_id)

            # -------------------------------------------------
            # Tool acceptance gate
            # -------------------------------------------------

            if not jsonld_defines_tool(raw_metadata):
                logger.warning(
                    "Rejecting Zenodo record %s: "
                    "JSON-LD does not describe "
                    "a software tool",
                    record_id,
                )

            # -------------------------------------------------
            # Extract / quality / persist
            # -------------------------------------------------

            tool_metadata = create_tool_metadata(
                record=record,
                raw_metadata=(raw_metadata),
                metadata_url=(metadata_url),
                pipeline_tag=(PIPELINE_TAG),
            )

            upsert_tool_metadata(
                session,
                tool_metadata,
            )

            session.commit()

            logger.info(
                "Stored Zenodo tool %s: %s (quality %.3f)",
                record_id,
                tool_metadata.title,
                tool_metadata.quality_score,
            )

            return HarvestResult(
                pipeline_tag=PIPELINE_TAG, record_ids=[record_id], failed_record_ids=[]
            )

        except Exception:
            session.rollback()

            logger.exception(
                "Failed to harvest Zenodo record %s",
                record_id,
            )

            raise


def main():
    parser = argparse.ArgumentParser(
        description=("Harvest a software tool from Zenodo JSON-LD")
    )

    parser.add_argument(
        "url",
        help=("Zenodo record URL, e.g. https://zenodo.org/records/22096936"),
    )

    args = parser.parse_args()

    pipeline_harvest_zenodo(args.url)


if __name__ == "__main__":
    main()
